### ISSUE TITLE
Fix

### ISSUE THREAD

**Issue by hmlongco** [QaziAmmar/SwiftUIFreezIssue#1]
Following appears to fix...

```swift
struct ListDetail: View, Equatable {
    static func == (lhs: ListDetail, rhs: ListDetail) -> Bool {
        lhs.item.id == rhs.item.id
    }
    ...
}
```

A new instance of ListDetail is created every time the list is diffed. This results in a new closure capture which Is different from the previous capture. Which causes the items in the list to be diffed. Which results in a new...

Loop.

Odd that it's apparently being compared as a POD. May have to dig further.

Note that when debugging I added an init to ListDetail and that showed the loop.
```swift
    init (item: Item, onSuccess: @escaping (Bool) -> Void) {
        self.item = item
        self.onSuccess = onSuccess
        print("Initialized with item: \(item)")
    }
```

**Comment by QaziAmmar** [comment]
Thank you for the detailed explanation and solution! Implementing the Equatable conformance and checking by id fixed the issue. I appreciate your help!
